### ISSUE TITLE
Add a soft closing of 'disable_open_new_dream'

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#100]
Right now it disable on client and server side - add another variable
`disable_open_new_dream_soft` that close only client vs the old `disable_open_new_dream` which close client and server.
Also make sure that all env var are CAPS - so turn `disable_open_new_dream_soft` to `DISABLE_OPEN_NEW_DREAM_SOFT`

**Comment by sh0oki** [comment]
Took care of it in `lockdown.yml`
