### ISSUE TITLE
Upon 'Add my name' -> show a small dialog

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#110]
The dialog would say:
"You want to help 'dream name'? Once you will approve we will send him a message with your mail so you can talk together and bring his dreams to the playa.
Yes! send my mail!"
Hebrew:
משהו כמו הודעה שאומרת
רוצה לעזור ל [שם החלום]? ברגע שתאשר, נשלח ל [שם החלום] הודעה עם המייל שלך ותוכלו לדבר ביניכם ולהביא חלומות לפלאייה
כפתור>> [אני מאשר לשלוח את המייל שלי]

**Comment by rootux** [comment]
And then an notification message that says:
Thank you. We've sent your mail to 'dream name' You are a wonderful man with great heart'
ואז הודעת תודה 
שלחנו את המייל שלך ל [שם החלום] 
אתה אדם נפלא וטוב לב

**Comment by sh0oki** [comment]
Closing, dup of #138
