### ISSUE TITLE
Add a checkbox 'Holy fuck! This dream is great. Send my contact details to the dreamer'

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#138]
Upon 'Donating to dream' Add checkbox that will be checked by default:
English:
'Holy fuck! This dream is great. Send my contact details to the dreamer'

Hebrew:
'הולי פאק! החלום הזה אדירר. שלח את פרטי הקשר שלי לבעל החלום'

The checkbox will be checked by default.
And if the user presses on the donate when it's checked then it will also 'click' on the 'Add my name to dream'

**Comment by sh0oki** [comment]
@rootux can I remove #124? This seems to cover it

**Comment by rootux** [comment]
Yes

**Comment by sh0oki** [comment]
from #110 
Thank you. We've sent your mail to 'dream name' You are a wonderful man with great heart'
ואז הודעת תודה
שלחנו את המייל שלך ל [שם החלום]
אתה אדם נפלא וטוב לב

**Comment by rootux** [comment]
לא החלפתי את הטקסט לאתה אדם נפלא וטוב. נעשה קופירייקט בעתיד
didn't replaced the text.
