### ISSUE TITLE
Reset password for spark

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#194]
If spark is enabled we should call the spark endpoint for reset password.
Right now can perhaps just redirect to the spark page of reset password.

**Comment by omerpines** [comment]
The user's password is coming from Drupal. 
So, we have 3 options to solve this:
1. Send them to Drupal reset password screen.
2. Create API call to send a reset password email from Drupal. 
3. Notify user that they need to go to profile.midburn.org if they want to reset their password.

@amotenko, this is a good usecase to consider...

**Comment by omerpines** [comment]
Currently #1 was selected.
@amotenko, in the last meeting, we discussed that this should be a Spark API call to reset password. Please open an issue for this.
