### ISSUE TITLE
Safety file PDF/Document (deadline: 30/3)

### ISSUE THREAD

**Issue by sh0oki** [Midburn/dreams#198]
We need to create a document with all dream fields required for safety assessment.
@rootux created an amazing Google Apps Script that does that, need to customize it a bit with the relevant list of questions.

  חלקים מתוך תוכנת החלומות שיש להפוך לקובץ:
עדיף לשים את השאלות ואת התשובות אין צורך לשים את ההסברים והפירוט של השאלות
שם חלום (מספיק רק עברית)
סיכום החלום במשפט (מספיק רק עברית)
תיאור מלא של הרעיון
פירוט טכני וניראות - הכל
תיאור פיזי
מידות
כיצד המיצב נראה
חיבור לחשמל - כולל פירוט (כל נושא החשמל)
כיצד יעברו כבלי החשמל
חשמל ביום
הספק המיצב
אופי היצירה - מספיק רק החלק של אינטראקטיביות
הפעלת אש
סאונד
מבקש להישרף
פוטנציאל ביצוע - תוכנית עבודה
תיק בטיחות כל הנושאים והשאלות:
אבקש לצרף את התמונות והשרטוטים שהאמנים העלו
צמ"ה
דגשי בטיחות(הכל) חומרי גלם
רשימת כלי עבודה
ציוד בטיחות
אמצעי מיגון
הרמת מיצב
קיבוע המיצב
אבטחת המיצב
מיגון חלקים נעים
שילוט

**Comment by basels** [comment]
שם חלום		:name
סיכום החלום במשפט:		:subtitle
תיאור מלא של הרעיון:		:description
פירוט טכני וניראות		
תיאור פיזי:		:spec_physical_description
מידות	אורך:	:spec_length
	רוחב:	:spec_width
	גובה:	:spec_height
כיצד המיצב נראה		:spec_visual_night_day
חיבור לחשמל - כולל פירוט (כל נושא החשמל)		
	האם המיצב דורש חיבור לחשמל?	:spec_is_electricity
	פירוט צרכני החשמל:	:spec_electricity_details
	כיצד יעברו כבלי החשמל ואיך יחוברו למקור המתח?	:spec_electricity_how
	האם יש צורך בחיבור לחשמל בשעות היום?	:spec_electricity_is_daytime
	מה ההספק שהמיצב צורך?	:spec_electricity_watt
אופי היצירה (אינטראקטיביות)		
	האם המיצב מערב הפעלת אש כחלק אינטגרלי ומהותי?	:dreamprop_interactivity_is_fire_present
	פירוט:	:dreamprop_interactivity_fire_present_desc
	האם המיצב 'יוצר' סאונד / רעש כלשהו?	:dreamprop_interactivity_is_sound
	פירוט:	:dreamprop_interactivity_sound_desc
	האם המיצב מבקש להישרף?	:dreamprop_interactivity_is_fire_event
	פירוט:	:dreamprop_interactivity_fire_event_desc
פוטנציאל ביצוע	מהי תכנית העבודה שלכם?	:dreamscholarship_execution_potential_work_plan
תיק בטיחות		
	תמונות ושרטוטים:	
	האם הקמת המיצב דורשת שימוש בצמ"ה?	:safety_is_heavy_equipment
דגשי בטיחות	רשימת חומרי הגלם הנדרשים:	:safety_materials
	רשימת כלי עבודה:	:safety_tools
	ציוד הבטיחות הנדרש לביצוע ההקמה:	:safety_equipment
	אופן בינוי אמצעי המיגון:	:safety_how_to_build_safety
	אופן הרמת המיצב:	:safety_how
	אופן קיבוע המייצב לקרקע:	:safety_grounding
	אופן אבטחת המיצב:	:safety_securing
	אופן מיגון חלקים נעים מפגיעה:	:safety_securing_parts
	שילוט אזהרה/הדרכה נדרש:	:safety_signs

**Comment by basels** [comment]
Done
