### ISSUE TITLE
Prepare system for art kickoff + 2018 event

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#239]

**Comment by rootux** [comment]
@omerpines what do you mean?

**Comment by omerpines** [comment]
1. Once new event functionality is available, display Event Midburn 2018 (archive 2017 but should still be available). 
2. Run flow of dreamer once to make sure it is working properly (after all improvements)
3. Fields that need change or add from last year?
4. Hearts functionality (on/off) needs to start at 0 for all users in the new event.
