### ISSUE TITLE
Sync project team members into Spark on project update (for record, ticketing and early arrival).

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#243]

**Comment by rootux** [comment]
We will call a POST endpoint that will verify using some key stored as an env variable in the server to protect security.
This will require 8h-12h

**Comment by omerpines** [comment]
I suggest to also validate each member added to a dream by calling Spark API.

**Comment by rootux** [comment]
Done on our side - Waiting for some response from Spark team
