### ISSUE TITLE
Links are viewed as simple text 

### ISSUE THREAD

**Issue by yossilan** [Midburn/dreams#279]
היי, עם מי אפשר לדבר לגבי מערכת "החלומות"? הרבה אנשים מעירים לנו על כך שהלינקים המתוארים בטקסט שלנו לא פעילים, אך נראה לנו שזו פשוט בעייה\מגבליה של המערכת תוכנה.... 

לדוגמא\בדיקה: https://dreams.midburn.org/dreams/295

**Comment by LioraNaginsky-zz** [comment]
Already opened the issue - #280 
We will handle ASAP.
I'm moving this issue to "closed" because it's duplicate.
