### ISSUE TITLE
Not active links 

### ISSUE THREAD

**Issue by LioraNaginsky-zz** [Midburn/dreams#280]
היי, עם מי אפשר לדבר לגבי מערכת "החלומות"? הרבה אנשים מעירים לנו על כך שהלינקים המתוארים בטקסט שלנו לא פעילים, אך נראה לנו שזו פשוט בעייה\מגבליה של המערכת תוכנה....

לדוגמא\בדיקה:
dream # 295

**Comment by LioraNaginsky-zz** [comment]
@enoodle 
1. links should be blue and with underline
2.will be opened in new tab

**Comment by enoodle** [comment]
closed by #284
