### ISSUE TITLE
To remove questions related to the hearts on the questions tab

### ISSUE THREAD

**Issue by LioraNaginsky-zz** [Midburn/dreams#297]
to hide all question and answers except from:
![image](https://user-images.githubusercontent.com/33637405/51919282-c6234e00-23eb-11e9-8179-293f9ecb7e7d.png)
 Also please update the English version

**Comment by phouri** [comment]
There is no english version :S 

Also seems like a lot of the English is broken

**Comment by LioraNaginsky-zz** [comment]
@phouri right there is no english version, but once we switch to English these questions shouldn't be displayed :)

**Comment by LioraNaginsky-zz** [comment]
checked and approved on staging
