### ISSUE TITLE
Email verification functionality

### ISSUE THREAD

**Issue by LioraNaginsky-zz** [Midburn/dreams#303]
To add email verification functionality for dream manager and team members:
"Once user will input his email address into email field - dreams system will check and verify email address via back end service.
*when email will be validated user will continue and if not user will get the error message and the field will be red.
for English version: "Sorry, but we couldn't find a Midburn profile associated with name@email.com"
for Hebrew version:
אופס! לא מצאנו פרופיל מידברן מקושר למייל"
name@email.com"

**Comment by NitayRabi** [comment]
@LioraNaginsky - Regarding 3. - full integration requires the user to log in through Spark and redirected to your app with correct cookie - then you send the user's token (extracted from the cookie) and the SPARK_SECRET_TOKEN on other requests - is this what you mean? or only 1 single route for email validation?

### By the way - there's a route open and used by volunteers for validating users emails through Drupal - you can see usage in [HERE](https://github.com/Midburn/Volunteers/blob/develop/server/spark/sparkApi.js) You can consult with @elad-lachmi with adding the correct env variable to allow this
