### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by LioraNaginsky-zz** [Midburn/dreams#310]
**People report:**
1. Pini removed the columns: tickets and early arrival but still we can see the values. Please remove it. **Already fixed by Erez.**
2. Once the name of dream manager is in Hebrew it's couldn't be shown in the report. 
![image](https://user-images.githubusercontent.com/33637405/52491689-5887d680-2bd0-11e9-8a48-655b2a0d30b9.png)

**Dreams report:**
1.To delete column:  crewsize.
2. To add fields:
שם הקבוצה/ אמן
שם המלאכית
אימייל המלאכית
לינק לחלום במערכת דרימס
שם מנהל הפרויקט 
מספר טלפון מנהל הפרויקט
אי-מייל מנהל הפרויקט
סטטוס החלום  after adding checkbox for dreams approval
Hebrew should be supported for all fields

**Comment by enoodle** [comment]
אצלי זה מופיע בעברית סבבה. אני זוכר שדיברנו על זה פעם. אני לא יודע לסדר את זה מעבר, צריך כנראה לנסות לפתוח בתוכנה אחרת.

**Comment by LioraNaginsky-zz** [comment]
> אצלי זה מופיע בעברית סבבה. אני זוכר שדיברנו על זה פעם. אני לא יודע לסדר את זה מעבר, צריך כנראה לנסות לפתוח בתוכנה א
 באיזה תוכנה היית מציע לפתוח ?

**Comment by enoodle** [comment]
זה לא בקשות הגיוניות כל כך לטופס על אנשים. אולי הם רוצים לעשות את זה בטופס של החלומות?

**Comment by LioraNaginsky-zz** [comment]
**People report:**
1. Fixed by Erez
2. Fixed by Liora
