### ISSUE TITLE
Technical Specs & Visibility - tab

### ISSUE THREAD

**Issue by LioraNaginsky-zz** [Midburn/dreams#314]
בסוף העמוד יש להוסיף את המשפט הבא:  

לשאלות ניתן לפנות לצוות הטכני בכתובת מייל: technicaltealart2018@gmail.com
For English version:
For any question please contant the technical team: technicaltealart2018@gmail.com

**Comment by enoodle** [comment]
בטוח שהאימייל עם 2018 ולא 2019?
