### ISSUE TITLE
Add safety file comments

### ISSUE THREAD

**Issue by rootux** [Midburn/dreams#77]
We need to do some UX and understand what is the best solution here.

Product thinking:
So we have 2 people roles in the system - The safety file. aka Guide - which will write the initial comments on the safety.
And the Dreamer which will act upon those comments.

What I have in mind - in the Show dream page add another section - Safety File - with all the fields from the safety - it's a new panel that is available only for the dream creator and the guides - The idea is to add a checkbox that can be marked by the guide as 'Passed' and also add a place where the guide can make comments on the 'safety' file - the Idea is that the dreamer can see it and act upon it.

I'm thinking whether the text box should be filled only by the guide or can the Dreamer also enter comments into that box - this may lead to situation where the dreamer 'deletes' the safety file comments which can be dangerous.
Yet otherwise the dreamer will need to announce the crew to recheck the safety sections.
Needs more Research on the Product side.

**Comment by rootux** [comment]
After a talk with Rotem bonder we got 2 versions:
Slim one - a text box that can be edited by the guide and should be shown to the dreamer.

Full one - Messaging. each dream would have messaging table that would allow the 'guides' to sent messages to the dreamers. inside the 'Me' page OR the dream page there will be a 'Messaging' part where messages from the system would be displayed - each message will take the 'email' of the guide who sent it so the user would know if it's safety or another person.
When user finished to update he can just send back a message - done - using the same text box.

**Comment by rootux** [comment]
So I think as a final solution we will go with a text box the can be edited by a guide and shown to dreamer (safety_file_comments in a new .panel div called 'Safety file comments'). something like #111
@sh0oki What do you think? and @basels Do you want to take this one? it's suppose to be the same as #111

**Comment by sh0oki** [comment]
Sounds good to me :)

**Comment by basels** [comment]
@rootux, @sh0oki sure :)
